name: Lint

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  toml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ">=3.11"
    - run: |
        python3 -c 'import tomllib; tomllib.load(open("accesser/config.toml", "rb"))'
